services:
  db:
    image: postgres:15
    container_name: videoconferencias_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: videoconferencias
    ports:
      - "5432:5432"
<<<<<<< HEAD
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-telemedicina_agendamiento}
      POSTGRES_USER: ${POSTGRES_USER:-admin_telemedicina}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password_seguro_123}
=======
>>>>>>> main
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
<<<<<<< HEAD
    container_name: api_telemedicina
    restart: unless-stopped
    depends_on:
      - db-postgres
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/app
    entrypoint: ["/bin/sh", "-c", "/usr/src/app/scripts/start.sh"]
    networks:
      - red-telemedicina

networks:
  red-telemedicina:
    driver: bridge
=======
    container_name: videoconferencias_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://admin:admin123@db:5432/videoconferencias
    depends_on:
      - db
>>>>>>> main

volumes:
  postgres_data: