@echo off
echo Iniciando el sistema de Telemedicina y Triaje...

echo Iniciando Servicio de Usuarios...
start "Usuarios" cmd /k "call venv\Scripts\activate && cd microservices\usuarios\servicio_usuarios && python app.py"

echo Iniciando Servicio de Agendamiento...
start "Agendamiento" cmd /k "call venv\Scripts\activate && cd microservices\agendamiento && python run.py"

echo Iniciando Servicio de Triage...
start "Triage" cmd /k "call venv\Scripts\activate && cd microservices\triage && python app.py"

echo Iniciando Servicio de Historial Medico...
start "Historial Medico" cmd /k "call venv\Scripts\activate && cd microservices\historial_medico && python run.py"

echo Iniciando Servicio de Videoconferencias...
start "Videoconferencias" cmd /k "call venv\Scripts\activate && cd microservices\videoconferencias && python app.py"

echo Iniciando Frontend (React)...
start "Frontend" cmd /k "cd frontend && npm start"

echo ¡Todos los servicios se están ejecutando en ventanas separadas!