# Usa una imagen base oficial de Python
FROM python:3.10-slim-buster

# Establece el directorio de trabajo dentro del contenedor
# Aquí, /app será la raíz de nuestro microservicio de agendamiento
WORKDIR /app

# Copia el archivo de requisitos e instala las dependencias
# Esto se hace primero para aprovechar el cache de Docker si los requisitos no cambian
COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Copia el resto del código de la aplicación al directorio de trabajo
COPY . .

# Configura variables de entorno para Flask
ENV FLASK_APP=app
ENV FLASK_ENV=production
ENV PYTHONUNBUFFERED=1

# Expone el puerto en el que se ejecutará la aplicación
EXPOSE 5000