"""Initial migration

Revision ID: e2aa78891eb2
Revises: 
Create Date: 2026-05-26 07:18:58.317523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2aa78891eb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialidades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('tipo_documento', sa.Enum('CC', 'TI', 'CE', 'PA', name='tipo_documento_enum'), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('genero', sa.Enum('M', 'F', 'O', name='genero_enum'), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pacientes_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_pacientes_numero_documento'), ['numero_documento'], unique=True)

    op.create_table('medicos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_registro', sa.String(length=30), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('especialidad_id', sa.Integer(), nullable=False),
    sa.Column('duracion_consulta_min', sa.Integer(), nullable=False),
    sa.Column('tarifa_consulta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['especialidad_id'], ['especialidades.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicos_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_medicos_especialidad_id'), ['especialidad_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicos_numero_registro'), ['numero_registro'], unique=True)

    op.create_table('agendamientos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_cita', sa.String(length=20), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('fecha_cita', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('tipo_consulta', sa.Enum('PRIMERA_VEZ', 'CONTROL', 'URGENCIA', 'SEGUIMIENTO', name='tipo_consulta_enum'), nullable=False),
    sa.Column('modalidad', sa.Enum('VIDEOCONSULTA', 'CHAT', 'TELEFONO', name='modalidad_enum'), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CONFIRMADA', 'EN_CURSO', 'COMPLETADA', 'CANCELADA', 'NO_ASISTIO', name='estado_agendamiento_enum'), nullable=False),
    sa.Column('motivo_consulta', sa.Text(), nullable=True),
    sa.Column('notas_adicionales', sa.Text(), nullable=True),
    sa.Column('motivo_cancelacion', sa.String(length=255), nullable=True),
    sa.Column('nivel_triaje', sa.Enum('VERDE', 'AMARILLO', 'NARANJA', 'ROJO', name='nivel_triaje_enum'), nullable=True),
    sa.Column('puntaje_triaje', sa.Integer(), nullable=True),
    sa.Column('enlace_videoconsulta', sa.String(length=500), nullable=True),
    sa.Column('sala_id', sa.String(length=100), nullable=True),
    sa.Column('recordatorio_enviado', sa.Boolean(), nullable=True),
    sa.Column('confirmado_por_paciente', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('hora_fin > hora_inicio', name='chk_cita_horario_valido'),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agendamientos', schema=None) as batch_op:
        batch_op.create_index('ix_agendamiento_fecha_medico', ['fecha_cita', 'medico_id'], unique=False)
        batch_op.create_index('ix_agendamiento_fecha_paciente', ['fecha_cita', 'paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendamientos_codigo_cita'), ['codigo_cita'], unique=True)
        batch_op.create_index(batch_op.f('ix_agendamientos_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendamientos_fecha_cita'), ['fecha_cita'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendamientos_medico_id'), ['medico_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendamientos_paciente_id'), ['paciente_id'], unique=False)

    op.create_table('disponibilidad_medico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Enum('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO', name='dia_semana_enum'), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('hora_fin > hora_inicio', name='chk_horario_valido'),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medico_id', 'dia_semana', 'hora_inicio', name='uq_medico_dia_hora')
    )
    with op.batch_alter_table('disponibilidad_medico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disponibilidad_medico_medico_id'), ['medico_id'], unique=False)

    op.create_table('historial_agendamientos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agendamiento_id', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=30), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=30), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('modificado_por', sa.String(length=100), nullable=True),
    sa.Column('fecha_cambio', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agendamiento_id'], ['agendamientos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historial_agendamientos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historial_agendamientos_agendamiento_id'), ['agendamiento_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_agendamientos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historial_agendamientos_agendamiento_id'))

    op.drop_table('historial_agendamientos')
    with op.batch_alter_table('disponibilidad_medico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disponibilidad_medico_medico_id'))

    op.drop_table('disponibilidad_medico')
    with op.batch_alter_table('agendamientos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agendamientos_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_agendamientos_medico_id'))
        batch_op.drop_index(batch_op.f('ix_agendamientos_fecha_cita'))
        batch_op.drop_index(batch_op.f('ix_agendamientos_estado'))
        batch_op.drop_index(batch_op.f('ix_agendamientos_codigo_cita'))
        batch_op.drop_index('ix_agendamiento_fecha_paciente')
        batch_op.drop_index('ix_agendamiento_fecha_medico')

    op.drop_table('agendamientos')
    with op.batch_alter_table('medicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicos_numero_registro'))
        batch_op.drop_index(batch_op.f('ix_medicos_especialidad_id'))
        batch_op.drop_index(batch_op.f('ix_medicos_email'))

    op.drop_table('medicos')
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pacientes_numero_documento'))
        batch_op.drop_index(batch_op.f('ix_pacientes_email'))

    op.drop_table('pacientes')
    op.drop_table('especialidades')
    # ### end Alembic commands ###
