services:
  # Microservicio de Agendamiento
  - type: web
    name: ms-agendamiento
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./scripts/start.sh
    rootDir: microservices/agendamiento
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: telemedicina-db
          property: connectionString
      - key: PORT
        value: 5000

  # Microservicio de Historial Médico
  - type: web
    name: ms-historial-medico
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    rootDir: microservices/historial_medico
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: telemedicina-db
          property: connectionString
      - key: PORT
        value: 5003

  # Microservicio de Videoconferencias
  - type: web
    name: ms-videoconferencias
    env: python
    buildCommand: pip install -r requirements.txt && python migrate_db.py
    startCommand: gunicorn app:app
    rootDir: microservices/videoconferencias
    envVars:
      - key: VIDEOCONFERENCIAS_DB_URL
        fromDatabase:
          name: telemedicina-db
          property: connectionString
      - key: PORT
        value: 5004

  # Frontend (React)
  - type: web
    name: telemedicina-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    rootDir: frontend
    envVars:
      - key: REACT_APP_AGENDAMIENTO_URL
        fromService:
          type: web
          name: ms-agendamiento
          property: url
      - key: REACT_APP_HISTORIAL_MEDICO_URL
        fromService:
          type: web
          name: ms-historial-medico
          property: url
      - key: REACT_APP_VIDEOCONFERENCIA_URL
        fromService:
          type: web
          name: ms-videoconferencias
          property: url

databases:
  - name: telemedicina-db
    databaseName: telemedicina
    user: admin
    plan: free
    region: oregon